export const ORDER_ITEM_REQUEST = "ORDER_ITEM_REQUEST";
export const ORDER_ITEM_SUCCESS = "ORDER_ITEM_SUCCESS";
export const ORDER_ITEM_FAILS = "ORDER_ITEM_FAILS";
export const ORDER_FETCH_REQUEST = "ORDER_FETCH_REQUEST";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";