export const ADD_TO_WHISHLIST_REQUEST = "ADD_TO_WHISHLIST_REQUEST";
export const ADD_TO_WHISHLIST = "ADD_TO_WHISHLIST";
export const WHISHLIST_ERROR = "WHISHLIST_ERROR";
export const GET_WHISHLIST_ITEMS_REQUEST = "GET_WHISHLIST_ITEMS_REQUEST";
export const GET_WHISHLIST_ITEMS_SUCCESS = "GET_WHISHLIST_ITEMS_SUCCESS";
export const GET_WHISHLIST_ITEMS_FAIL = "GET_WHISHLIST_ITEMS_FAIL";
export const REMOVE_TO_WHISHLIST = "REMOVE_TO_WHISHLIST";
export const REMOVE_TO_WHISHLIST_FAIL = "REMOVE_TO_WHISHLIST_FAIL";